name: Scully Publish to GH-Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jruipinto/ImageMagick-action@v0.2-alpha
        with:
          # ImageMagick command to be executed
          command: mogrify -path src/assets/ -auto-orient -resize x500 src/assets/*.jpg
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: --base-href /
